version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Lint-JS started on `date`
      - npm run lint-js
      - echo Lint-CSS started on `date`
      - npm run lint-css
      - echo Test started on `date`
      - npm run test
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo List the project files
      - ls
      - echo List the bucket files
      - aws s3 ls s3://jerrythimothy.com
      # - aws s3 rm --recursive s3://jerrythimothy.com/
      - aws s3 sync build/ s3://jerrythimothy.com   
artifacts:
  files:
    - '**/*'
  base-directory: build