version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo List the project files
      - ls
      - echo List the bucket files
      - aws s3 ls s3://jerrythimothy.com
      # Delete object from bucket
      - aws s3 rm --recursive s3://jerrythimothy.com/ 
      # copy the contents of /build to S3
      - aws s3 cp --recursive ./build s3://jerrythimothy.com/ 
      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      # - >
      #   aws s3 cp --acl public-read 
      #   --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
      #   ./build/service-worker.js s3://jerrythimothy.com/
      # # set the cache-control headers for index.html to prevent
      # # browser caching
      # - >
      #   aws s3 cp --acl public-read 
      #   --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
      #   ./build/index.html s3://jerrythimothy.com/
artifacts:
  files:
    - '**/*'
  base-directory: build